trigger:
  branches:
    include:
    - master
  paths:
    include:
    - debian

jobs:

- job: Docker

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: github_docker
      repository: a224327780/debian
      Dockerfile: '**/debian'
      tags: 'latest'
