trigger:
  branches:
    include:
    - master
  paths:
    include:
    - php/

jobs:

- job: PHP

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: github_docker
      repository: a224327780/php
      Dockerfile: '**/php/Dockerfile'
      tags: 'latest'
