trigger:
  branches:
    include:
    - master
  paths:
    include:
    - redis/

jobs:

- job: Redis

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: github_docker
      repository: a224327780/redis
      Dockerfile: '**/redis/Dockerfile'
      tags: 'latest'
