name: PHP

on:
  push:
    branches: [ master ]
    paths:
      - 'php/**'
      - '**/php.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./php/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/a224327780/php:latest
            ghcr.io/a224327780/php:7.4
            caoyufei/php:latest
            caoyufei/php:7.4
